-- clearing database
DROP TABLE vote CASCADE CONSTRAINTS;
DROP TABLE joinsCommunity CASCADE CONSTRAINTS;
DROP TABLE follows CASCADE CONSTRAINTS;
DROP TABLE givenToBy CASCADE CONSTRAINTS;
DROP TABLE messageSentByIn CASCADE CONSTRAINTS;
DROP TABLE joinsChatRoom CASCADE CONSTRAINTS;
DROP TABLE chatRoom CASCADE CONSTRAINTS;
DROP TABLE commentOn CASCADE CONSTRAINTS;
DROP TABLE postIn CASCADE CONSTRAINTS;
DROP TABLE entryCreatedBy CASCADE CONSTRAINTS;
DROP TABLE communities CASCADE CONSTRAINTS;
DROP TABLE users CASCADE CONSTRAINTS;
DROP TABLE award CASCADE CONSTRAINTS;
DROP TABLE USERSAGE CASCADE CONSTRAINTS;
DROP TABLE IMAGECONTAINEDBY CASCADE CONSTRAINTS;
DROP TABLE VIDEOCONTAINEDBY CASCADE CONSTRAINTS;